// Typing content organized by difficulty and type

// Words for kids - organized by difficulty
const typingWords = {
    easy: [
        "cat", "dog", "run", "fun", "sun", "hat", "big", "red",
        "yes", "mom", "dad", "boy", "toy", "car", "bed", "leg",
        "egg", "bag", "fox", "box", "top", "hot", "wet", "pen"
    ],
    medium: [
        "apple", "happy", "puppy", "family", "jumping", "school",
        "friend", "yellow", "purple", "orange", "bunny", "cookie",
        "garden", "rocket", "planet", "monkey", "dragon", "castle",
        "rainbow", "butterfly", "dinosaur", "treasure", "adventure"
    ],
    hard: [
        "elephant", "wonderful", "beautiful", "playground", "celebrate",
        "magnificent", "incredible", "superhero", "mysterious", "exciting",
        "friendship", "imagination", "explorer", "fantastic", "spectacular",
        "adventure", "discovery", "understand", "butterfly", "neighborhood"
    ]
};

// Sentences for kids - organized by difficulty
const typingSentences = {
    easy: [
        "I like cats.",
        "The dog runs fast.",
        "We play in the sun.",
        "Mom is nice.",
        "I see a red ball.",
        "The toy is fun.",
        "Dad can jump high.",
        "I have a pet.",
        "She has a hat.",
        "We eat good food."
    ],
    medium: [
        "I love playing with my friends.",
        "The rainbow has many colors.",
        "My puppy is very happy today.",
        "We are going to the park.",
        "I can jump and run fast.",
        "The dragon flies in the sky.",
        "My favorite color is purple.",
        "I see a beautiful butterfly.",
        "We have fun at school.",
        "The bunny hops around the garden."
    ],
    hard: [
        "My imagination takes me on wonderful adventures.",
        "The superhero saved the city from danger.",
        "We discovered a mysterious treasure in the castle.",
        "The magnificent elephant walked through the jungle.",
        "My neighborhood has a fantastic playground.",
        "I celebrate my birthday with family and friends.",
        "The spectacular fireworks lit up the night sky.",
        "Exploring new places is incredibly exciting.",
        "Understanding kindness makes the world better.",
        "The beautiful butterfly landed on the colorful flower."
    ]
};

// Paragraphs for kids - organized by difficulty
const typingParagraphs = {
    easy: [
        "I have a cat. My cat is soft. She likes to play. I love my cat.",
        "The sun is up. It is a nice day. We can go out and play. Let's have fun!",
        "My mom is kind. My dad is fun. I love my family. They take care of me.",
        "I like to read books. Books are fun. They tell great stories. Reading is cool!"
    ],
    medium: [
        "Today is a wonderful day! The sun is shining and the birds are singing. I am going to the park with my friends. We will play on the swings and go down the slide. I can't wait to have fun!",
        "My puppy is the best pet ever. She has soft brown fur and big happy eyes. Every morning she wakes me up with kisses. We play fetch in the backyard together. I love my puppy so much!",
        "Learning to type is like going on an adventure. At first it feels tricky, but practice makes it easier. Soon your fingers will know where to go. Keep trying and you will be amazing!",
        "Dinosaurs lived long ago. Some were big and some were small. They walked on the earth before people. Now we find their bones and learn about them. Dinosaurs are really cool!"
    ],
    hard: [
        "Once upon a time, there was a brave little explorer who loved discovering new things. Every day brought a new adventure filled with mystery and excitement. With courage and imagination, nothing seemed impossible. The explorer knew that being kind and curious would lead to the most spectacular discoveries of all.",
        "In the magical kingdom, there lived a wise dragon who protected the castle. The dragon was magnificent with shimmering scales that sparkled in the sunlight. All the villagers respected the dragon because it was friendly and helpful. Together they celebrated their wonderful friendship every year with a grand festival.",
        "The incredible superhero soared through the sky above the neighborhood. With super strength and amazing abilities, the hero kept everyone safe from danger. But the most important power was the hero's big heart and kindness. Understanding that helping others was the greatest gift, the superhero inspired everyone to be brave.",
        "Deep in the enchanted forest, a beautiful butterfly discovered a hidden treasure. The treasure wasn't gold or jewels, but something even more valuable - the gift of friendship. As the butterfly explored the mysterious woods, it met wonderful creatures who taught important lessons about sharing and caring. This adventure became a spectacular journey of discovery and joy."
    ]
};

// Kid-friendly themes for motivation
const typingThemes = {
    animals: ["🐶", "🐱", "🦁", "🐘", "🦒", "🐼", "🐨", "🦋", "🐝", "🐸"],
    food: ["🍎", "🍌", "🍪", "🍕", "🍦", "🍰", "🍇", "🍓", "🥕", "🌽"],
    space: ["🚀", "🌟", "🌙", "⭐", "🪐", "🛸", "👽", "🌍", "☄️", "🌠"],
    fantasy: ["🦄", "🐉", "🏰", "👑", "🗡️", "🧙", "🧚", "🦖", "🧜", "🧞"]
};

// Progress milestones for encouragement
const milestones = [
    { words: 5, message: "Great start! Keep going!", emoji: "🌟" },
    { words: 10, message: "You're doing awesome!", emoji: "🎉" },
    { words: 20, message: "Wow! You're a typing star!", emoji: "⭐" },
    { words: 30, message: "Incredible! You're amazing!", emoji: "🏆" },
    { words: 50, message: "Superstar typist! Fantastic!", emoji: "🎊" },
    { words: 100, message: "100 words! You're unstoppable!", emoji: "🚀" }
];

// Progressive Typing Lessons - Teaching proper finger placement
const typingLessons = [
    {
        id: 1,
        title: "Home Row Foundation",
        description: "Learn the home row keys where your fingers rest",
        emoji: "🏠",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';'],
        fingerGuide: "Left: Pinky(A) Ring(S) Middle(D) Index(F) | Right: Index(J) Middle(K) Ring(L) Pinky(;)",
        words: ["aaa", "sss", "ddd", "fff", "jjj", "kkk", "lll", ";;;",
                "asd", "jkl", "asdf", "jkl;", "fdsa", "lkj;",
                "sad", "lad", "dad", "fad", "add", "all", "fall", "ask", "flask", "lass",
                "sad", "lad", "dad", "fad", "add", "all", "fall", "ask", "flask", "lass",
                "glass", "salad", "sal", "las", "fas", "fals", "alfa", "alfalfa",
                "aaa", "sss", "ddd", "fff", "jjj", "kkk", "lll", "asd", "jkl",
                "ask", "sad", "lad", "dad", "add", "all", "fall", "flask", "lass", "glass",
                "ads", "fads", "lads", "adds", "alls", "falls", "asks", "salads",
                "ssss", "dddd", "ffff", "jjjj", "kkkk", "llll", "aaaa",
                "ask", "sad", "lad", "dad", "add", "all", "fall", "flask", "lass", "glass",
                "alas", "slash", "flashs", "salsa", "salsas", "flags", "sag", "saga"],
        instructions: "Place your fingers on the home row. Left pinky on A, right pinky on ;. Keep your fingers curved!"
    },
    {
        id: 2,
        title: "Home Row Master",
        description: "Practice all home row keys with simple words",
        emoji: "✨",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';'],
        words: ["ask", "sad", "lad", "dad", "add", "all", "fall", "class", "flask", "glass",
                "salad", "asks", "lass", "glad", "flag", "jas", "jak", "jaks", "jask",
                "fall", "falls", "all", "alls", "sad", "sads", "lad", "lads", "dad", "dads",
                "glass", "flask", "class", "salad", "salads", "flags", "slag", "slags",
                "ask", "asks", "lass", "lass", "glad", "glas", "flask", "flasks",
                "add", "adds", "fall", "falls", "all", "alls", "sad", "sads",
                "aaa", "sss", "ddd", "fff", "jjj", "kkk", "lll", "asdf", "jkl;",
                "asdfasdf", "jkl;jkl;", "asdffdsa", "jkl;;lkj",
                "glad", "lads", "dads", "adds", "alls", "falls", "asks", "lass",
                "salad", "salads", "glass", "flask", "flasks", "flags", "flag", "slags",
                "ask", "sad", "lad", "dad", "add", "all", "fall", "flask", "lass", "glass",
                "alas", "alfa", "alfalfa", "salsa", "salsas", "gal", "gals", "slag",
                "fall", "falls", "all", "alls", "sad", "sads", "lad", "lads", "dad", "dads"],
        instructions: "Type words using only home row keys. Keep your wrists straight!"
    },
    {
        id: 3,
        title: "Index Finger Reach Up",
        description: "Add R, U, T, Y - stretch your index fingers up",
        emoji: "👆",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';', 'R', 'U', 'T', 'Y'],
        words: ["try", "rut", "fry", "rat", "tar", "fur", "jar", "jut", "just", "rust",
                "tray", "stay", "dark", "fast", "rest", "yard", "start", "today",
                "rrr", "uuu", "ttt", "yyy", "rut", "try", "fry", "rat", "tar", "fur",
                "art", "arts", "tar", "tars", "rat", "rats", "rut", "ruts", "rust", "rusts",
                "fry", "frys", "try", "trys", "fur", "furs", "jar", "jars", "just", "jut",
                "fast", "last", "rust", "dust", "just", "trust", "start", "stars", "stay",
                "tray", "trays", "stray", "strays", "ray", "rays", "day", "days", "lay",
                "far", "surf", "turf", "yard", "yards", "ray", "rays", "fray", "frays",
                "raft", "rafts", "daft", "draft", "drafts", "shaft", "shafts", "staff",
                "art", "start", "star", "stay", "tray", "stray", "ray", "day", "far", "tar",
                "just", "dust", "rust", "trust", "fast", "last", "yard", "ray", "fray",
                "rut", "try", "fry", "rat", "tar", "fur", "jar", "jut", "just", "rust",
                "aft", "raft", "daft", "draft", "staff", "lasts", "fasts", "ruts", "rusts"],
        instructions: "Your index fingers move up to press R(left) and U(right). Return to home row after each key!"
    },
    {
        id: 4,
        title: "Middle Row Fingers",
        description: "Add E, I - middle fingers reach up",
        emoji: "☝️",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';', 'R', 'U', 'T', 'Y', 'E', 'I'],
        words: ["tie", "die", "eye", "red", "led", "fed", "ride", "fire", "tire", "uite",
                "idea", "side", "date", "kite", "like", "take", "real", "read",
                "eee", "iii", "tie", "die", "lie", "red", "led", "fed", "ride", "fire",
                "tire", "sire", "idea", "side", "slide", "date", "kite", "like", "take",
                "tree", "free", "see", "feed", "seed", "deed", "feet", "feel", "deer",
                "real", "read", "reader", "suit", "fruit", "juice", "iate", "rite",
                "file", "tile", "dial", "trial", "field", "yield", "safe", "life",
                "raise", "tried", "fried", "dried", "tied", "diet", "quite", "quiet",
                "star", "stare", "stir", "sure", "lure", "true", "rule", "rude",
                "tire", "tires", "fire", "fires", "ride", "rides", "side", "sides",
                "tide", "tides", "kite", "kites", "like", "likes", "take", "takes",
                "tale", "tales", "sale", "sales", "file", "files", "tile", "tiles",
                "read", "reads", "lead", "leads", "real", "ideal", "ideas", "fear", "fears",
                "seed", "seeds", "feed", "feeds", "feel", "feels", "feet", "tree", "trees",
                "free", "frees", "see", "deer", "dear", "fear", "year", "years"],
        instructions: "Middle fingers stretch up for E(left) and I(right). Keep other fingers on home row!"
    },
    {
        id: 5,
        title: "Top Row Complete",
        description: "Add W, O, Q, P - complete the top row",
        emoji: "🎯",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';', 'R', 'U', 'T', 'Y', 'E', 'I', 'W', 'O', 'Q', 'P'],
        words: ["wow", "pow", "row", "paw", "owl", "down", "town", "open", "rope", "hope",
                "wipe", "wide", "quite", "quote", "power", "tower", "quiet", "queue",
                "www", "ooo", "qqq", "ppp", "wow", "pow", "row", "paw", "owl", "owls",
                "who", "how", "now", "low", "slow", "flow", "show", "window", "yellow",
                "past", "pass", "play", "pray", "tray", "wrap", "drew", "drew", "sword",
                "put", "quit", "quite", "quote", "quotes", "oup", "soap", "road", "load",
                "pole", "role", "whole", "wrote", "poor", "door", "floor", "proof",
                "loop", "pool", "tool", "fool", "spool", "stool", "drool", "proof",
                "petal", "total", "equal", "sequel", "operas", "proper", "popular",
                "power", "powers", "tower", "towers", "lower", "lower", "slower", "flower",
                "widow", "widows", "window", "windows", "weird", "wired", "tired", "fired",
                "quest", "quests", "quiet", "quiets", "queue", "queues", "quake", "quakes",
                "people", "purple", "purpose", "pursue", "putrid", "poodle", "paddle",
                "water", "waiter", "waiters", "waste", "pasture", "rapture", "posture",
                "opera", "operas", "operate", "operated", "operator", "operators", "optimal"],
        instructions: "Ring fingers for W and O, pinkies for Q and P. Stretch and return!"
    },
    {
        id: 6,
        title: "Bottom Row Start",
        description: "Add V, M, C, N - reach down with index and middle",
        emoji: "👇",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';', 'R', 'U', 'T', 'Y', 'E', 'I', 'W', 'O', 'Q', 'P', 'V', 'M', 'C', 'N'],
        words: ["van", "man", "can", "vim", "vat", "mat", "cat", "name", "came", "main",
                "movie", "move", "mice", "nice", "voice", "manic", "comic", "music",
                "vvv", "mmm", "ccc", "nnn", "van", "vans", "man", "mans", "can", "cans",
                "vim", "vat", "vats", "mat", "mats", "cat", "cats", "name", "names",
                "came", "come", "main", "mane", "mine", "vine", "vein", "veins",
                "movie", "movies", "move", "moves", "mice", "nice", "nicer", "voice",
                "voices", "manic", "comic", "comics", "music", "musician", "musicians",
                "camp", "camps", "clamp", "clamps", "cream", "creams", "crime", "crimes",
                "victim", "victims", "victor", "victory", "vin", "vine", "vines", "civic",
                "common", "conform", "concern", "concert", "concern", "connect", "convenience",
                "commerce", "commute", "compete", "complete", "complain", "complex", "component",
                "moon", "moons", "noon", "noons", "oon", "corn", "corns", "core", "cores",
                "calm", "calms", "certain", "curtain", "curtains", "captain", "captains",
                "modern", "modem", "modems", "motion", "motions", "mention", "mentions",
                "numeric", "umerics", "uncover", "unicorn", "unicorns", "universe", "universal"],
        instructions: "Reach down: V(left index), C(left middle), N(right index), M(right index)"
    },
    {
        id: 7,
        title: "Bottom Row Complete",
        description: "Add Z, X, comma, period, slash",
        emoji: "⬇️",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';', 'R', 'U', 'T', 'Y', 'E', 'I', 'W', 'O', 'Q', 'P',
               'V', 'M', 'C', 'N', 'Z', 'X', ',', '.', '/'],
        words: ["zoo", "zip", "zap", "zone", "zero", "doze", "mix", "wax", "max", "next",
                "oxen", "cozy", "lazy", "crazy", "exam", "proxy", "taxi",
                "zzz", "xxx", ",,,", "...", "///", "zoo", "zoos", "zip", "zips", "zap",
                "zaps", "zone", "zones", "zero", "zeros", "doze", "dozes", "dozen",
                "mix", "mixes", "wax", "waxes", "max", "next", "text", "texts", "vex",
                "oxen", "oxygen", "cozy", "lazy", "crazy", "maze", "mazes", "amaze",
                "exam", "exams", "example", "examples", "complex", "complexes", "excellent",
                "proxy", "proxies", "taxi", "taxis", "toxic", "toxin", "toxins",
                "fix", "fixes", "fixed", "fixer", "fixers", "fixture", "fixtures",
                "freeze", "freezer", "freezers", "froze", "frozen", "prize", "prizes",
                "exercise", "exercize", "expertise", "expert", "experts", "expire", "expires",
                "relax", "relaxed", "waxed", "taxed", "vexed", "mixed", "fixed", "amazed",
                "exact", "examine", "excel", "execute", "executed", "execution", "excuse",
                "apex", "approx", "index", "reflex", "complex", "duplex", "perplex",
                "cozy, warm, nice.", "lazy, crazy, fun.", "zoo, taxi, maze."],
        instructions: "Complete the bottom row: Z(left pinky), X(left ring), ,(right middle), .(right ring), /(right pinky)"
    },
    {
        id: 8,
        title: "Letter Master",
        description: "Practice all letters together!",
        emoji: "🔤",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';', 'R', 'U', 'T', 'Y', 'E', 'I', 'W', 'O', 'Q', 'P',
               'V', 'M', 'C', 'N', 'Z', 'X', 'B', 'G', 'H', ',', '.', '/'],
        words: ["quick", "brown", "fox", "jumps", "over", "lazy", "dog", "the", "best", "way",
                "learn", "type", "practice", "every", "day", "have", "fun", "keep", "going",
                "the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog", "amazing",
                "beautiful", "challenge", "develop", "excellent", "fantastic", "genuine",
                "happy", "incredible", "joyful", "knowledge", "lovely", "magnificent",
                "natural", "optimistic", "peaceful", "quality", "remarkable", "superb",
                "wonderful", "expert", "youthful", "zealous", "bright", "creative",
                "hello", "world", "keyboard", "typing", "fingers", "practice", "lesson",
                "begin", "beginner", "boxing", "express", "explore", "galaxy", "github",
                "hamburger", "improve", "journey", "justice", "knight", "language",
                "maximum", "neighbor", "objective", "penguin", "question", "rainbow",
                "saxophone", "textbook", "umbrella", "vitamin", "whisper", "xylophone",
                "yesterday", "zephyr", "amazing", "brave", "climb", "danger", "elephant",
                "family", "garden", "hungry", "imagine", "jacket", "kingdom", "listen",
                "mountain", "newspaper", "organize", "puzzle", "question", "rainbow",
                "sunshine", "together", "universe", "vacation", "wonderful", "explore",
                "ability", "bravery", "challenge", "develop", "education", "freedom",
                "growth", "happiness", "inspiration", "knowledge", "learning", "miracle"],
        instructions: "You know all the letters! Practice typing real words with proper finger placement."
    },
    {
        id: 9,
        title: "Numbers Row",
        description: "Learn to type numbers 0-9",
        emoji: "🔢",
        keys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
        words: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "10", "20", "50", "100",
                "123", "456", "789", "2024", "1234", "5678",
                "111", "222", "333", "444", "555", "666", "777", "888", "999", "000",
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "0",
                "12", "23", "34", "45", "56", "67", "78", "89", "90", "01",
                "10", "20", "30", "40", "50", "60", "70", "80", "90", "100",
                "11", "22", "33", "44", "55", "66", "77", "88", "99", "00",
                "123", "234", "345", "456", "567", "678", "789", "890", "901",
                "321", "432", "543", "654", "765", "876", "987", "098", "109",
                "100", "200", "300", "400", "500", "600", "700", "800", "900",
                "1000", "2000", "3000", "4000", "5000", "6000", "7000", "8000", "9000",
                "1234", "2345", "3456", "4567", "5678", "6789", "7890", "8901", "9012",
                "12345", "23456", "34567", "45678", "56789", "67890", "78901", "89012",
                "2024", "2025", "1999", "2000", "1980", "1990", "2010", "2015", "2020",
                "101", "202", "303", "404", "505", "606", "707", "808", "909",
                "1357", "2468", "13579", "24680", "147", "258", "369", "159", "357"],
        instructions: "Stretch your fingers up to the number row. Use the same fingers as the letters below!"
    },
    {
        id: 10,
        title: "Special Characters",
        description: "Master special characters and symbols",
        emoji: "⚡",
        keys: ['-', '=', '[', ']', '\\', '\'', ',', '.', '/'],
        words: ["don't", "can't", "it's", "I'm", "[test]", "hi!", "wow?", "yes,", "no.",
                "fun!", "cool!", "great!",
                "---", "===", "[[[", "]]]", "\\\\\\", "'''", ",,,", "...", "///",
                "don't", "can't", "won't", "isn't", "aren't", "wasn't", "weren't",
                "I'm", "I'll", "I've", "I'd", "you're", "you'll", "you've", "you'd",
                "he's", "he'll", "he'd", "she's", "she'll", "she'd", "it's", "it'll",
                "we're", "we'll", "we've", "we'd", "they're", "they'll", "they've",
                "hello, world!", "yes, please.", "no, thanks.", "wow, amazing!",
                "[test]", "[hello]", "[world]", "[example]", "[practice]", "[lesson]",
                "path/to/file", "home/user/docs", "root/folder/name", "usr/bin/local",
                "one-two", "three-four", "five-six", "well-known", "self-made",
                "up-to-date", "state-of-the-art", "out-of-the-box", "user-friendly",
                "x = 1", "y = 2", "z = 3", "a = b", "c = d", "total = sum",
                "hi!", "bye!", "wow!", "cool!", "great!", "awesome!", "perfect!",
                "what?", "why?", "how?", "when?", "where?", "really?", "sure?",
                "yes, I can.", "no, I can't.", "hello, friend!", "goodbye, world!"],
        instructions: "Learn special characters used in everyday typing. Practice makes perfect!"
    },
    {
        id: 11,
        title: "Typing Champion",
        description: "Free practice with all keys!",
        emoji: "🏆",
        keys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', ';', 'R', 'U', 'T', 'Y', 'E', 'I', 'W', 'O', 'Q', 'P',
               'V', 'M', 'C', 'N', 'Z', 'X', 'B', 'G', 'H', ',', '.', '/', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
        words: ["You", "are", "amazing!", "Keep", "practicing", "every", "day", "and", "you", "will",
                "become", "a", "super", "fast", "typist!", "Great", "job!", "123", "wonderful!",
                "The", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog.", "Perfect!",
                "Pack", "my", "box", "with", "five", "dozen", "liquor", "jugs.", "Excellent!",
                "How", "vexingly", "quick", "daft", "zebras", "jump!", "Amazing", "work!",
                "Typing", "is", "fun!", "Practice", "makes", "perfect.", "You're", "doing", "great!",
                "Keep", "going!", "Never", "give", "up!", "You", "can", "do", "it!", "Believe!",
                "Amazing", "journey", "1234567890", "keyboard", "master", "2024", "champion!",
                "Congratulations!", "You've", "mastered", "all", "the", "keys!", "Fantastic!",
                "Now", "you", "can", "type", "anything!", "Letters,", "numbers,", "symbols!",
                "hello@example.com", "www.typing.com", "C:\\Users\\Documents", "/home/user/",
                "Don't", "stop", "now!", "Keep", "practicing!", "You're", "a", "superstar!",
                "The", "journey", "of", "1000", "miles", "begins", "with", "a", "single", "step.",
                "Practice", "makes", "perfect,", "and", "you're", "proving", "it", "every", "day!",
                "Skill", "+", "Practice", "=", "Mastery!", "You've", "got", "this!", "Amazing!",
                "You", "typed", "your", "way", "to", "success!", "Well", "done,", "champion!",
                "From", "A", "to", "Z,", "from", "0", "to", "9,", "you", "know", "them", "all!",
                "Every", "keystroke", "brings", "you", "closer", "to", "perfection!", "Brilliant!",
                "Remember:", "fingers", "on", "home", "row,", "look", "at", "screen,", "not", "keys!",
                "You're", "not", "just", "typing,", "you're", "creating", "magic", "with", "keys!"],
        instructions: "You're a typing master! Use all keys with confidence and speed!"
    }
];
